{"uri":"file:///home/tarcisio/dev/phpfin/vendor/symfony/filesystem/Exception/IOException.php","root":{"kind":0,"name":"","children":[{"kind":512,"name":"Symfony\\Component\\Filesystem\\Exception","location":[11,0,11,49]},{"kind":1,"name":"Symfony\\Component\\Filesystem\\Exception\\IOException","location":[20,0,38,1],"associated":[{"kind":1,"name":"RuntimeException"},{"kind":2,"name":"Symfony\\Component\\Filesystem\\Exception\\IOExceptionInterface"}],"description":"Exception class thrown when a filesystem operation failure happens.","children":[{"kind":16,"name":"$path","modifiers":4,"location":[22,12,22,17],"scope":"Symfony\\Component\\Filesystem\\Exception\\IOException"},{"kind":32,"name":"__construct","modifiers":1,"location":[24,4,29,5],"scope":"Symfony\\Component\\Filesystem\\Exception\\IOException","children":[{"kind":128,"name":"$message","location":[24,32,24,40],"scope":"__construct"},{"kind":128,"name":"$code","location":[24,42,24,51],"scope":"__construct","value":"0"},{"kind":128,"name":"$previous","location":[24,53,24,80],"scope":"__construct","value":"null","typeSource":1,"type":"Exception"},{"kind":128,"name":"$path","location":[24,82,24,94],"scope":"__construct","value":"null"}]},{"kind":32,"name":"getPath","modifiers":1,"location":[34,4,37,5],"description":"{@inheritdoc}","scope":"Symfony\\Component\\Filesystem\\Exception\\IOException"}]}]}}