{"uri":"file:///home/tarcisio/dev/phpfin/vendor/symfony/debug/FatalErrorHandler/FatalErrorHandlerInterface.php","root":{"kind":0,"name":"","children":[{"kind":512,"name":"Symfony\\Component\\Debug\\FatalErrorHandler","location":[11,0,11,52]},{"kind":1,"name":"FatalErrorException","modifiers":4096,"location":[13,4,13,57],"associated":[{"kind":1,"name":"Symfony\\Component\\Debug\\Exception\\FatalErrorException"}]},{"kind":2,"name":"Symfony\\Component\\Debug\\FatalErrorHandler\\FatalErrorHandlerInterface","location":[20,0,31,1],"description":"Attempts to convert fatal errors to exceptions.","children":[{"kind":32,"name":"handleError","modifiers":1,"location":[30,4,30,78],"description":"Attempts to convert an error into an exception.","scope":"Symfony\\Component\\Debug\\FatalErrorHandler\\FatalErrorHandlerInterface","type":"Symfony\\Component\\Debug\\Exception\\FatalErrorException|null","children":[{"kind":128,"name":"$error","location":[30,32,30,44],"description":"An array as returned by error_get_last()","scope":"handleError","type":"array"},{"kind":128,"name":"$exception","location":[30,46,30,76],"description":"A FatalErrorException instance\n","scope":"handleError","typeSource":1,"type":"Symfony\\Component\\Debug\\Exception\\FatalErrorException"}]}]}]}}