{"uri":"file:///home/tarcisio/dev/phpfin/vendor/symfony/filesystem/Tests/ExceptionTest.php","root":{"kind":0,"name":"","children":[{"kind":512,"name":"Symfony\\Component\\Filesystem\\Tests","location":[11,0,11,45]},{"kind":1,"name":"TestCase","modifiers":4096,"location":[13,4,13,30],"associated":[{"kind":1,"name":"PHPUnit\\Framework\\TestCase"}]},{"kind":1,"name":"IOException","modifiers":4096,"location":[14,4,14,54],"associated":[{"kind":1,"name":"Symfony\\Component\\Filesystem\\Exception\\IOException"}]},{"kind":1,"name":"FileNotFoundException","modifiers":4096,"location":[15,4,15,64],"associated":[{"kind":1,"name":"Symfony\\Component\\Filesystem\\Exception\\FileNotFoundException"}]},{"kind":1,"name":"Symfony\\Component\\Filesystem\\Tests\\ExceptionTest","location":[20,0,46,1],"associated":[{"kind":1,"name":"PHPUnit\\Framework\\TestCase"}],"description":"Test class for Filesystem.","children":[{"kind":32,"name":"testGetPath","modifiers":1,"location":[22,4,26,5],"scope":"Symfony\\Component\\Filesystem\\Tests\\ExceptionTest"},{"kind":32,"name":"testGeneratedMessage","modifiers":1,"location":[28,4,33,5],"scope":"Symfony\\Component\\Filesystem\\Tests\\ExceptionTest"},{"kind":32,"name":"testGeneratedMessageWithoutPath","modifiers":1,"location":[35,4,39,5],"scope":"Symfony\\Component\\Filesystem\\Tests\\ExceptionTest"},{"kind":32,"name":"testCustomMessage","modifiers":1,"location":[41,4,45,5],"scope":"Symfony\\Component\\Filesystem\\Tests\\ExceptionTest"}]}]}}